### ISSUE TITLE
Easier way

### ISSUE THREAD

**Issue by NaiJii** [techiew/UniversalProxyDLL#5]
Check this out
[https://github.com/mrexodia/perfect-dll-proxy/](url)

**Comment by techiew** [comment]
Interesting. I remember I was looking a long time for a way to do /EXPORT linker comments that automatically selected the system drive. This was actually the main reason I made UPD since I could not find a solution at the time.

UPD is different in some ways:
- UPD allows function hooking/interception
- The DLL to proxy can be found dynamically and not just in one path, UPD somewhat mimics the normal DLL search order to do this

But if neither of those are needed then mrexodia's solution is definitely better.

True perfection would be to copy the target DLL's export table into the proxy DLL's export table at runtime. That way you would need no predefined exports at all - except that you'd need a ton of dummy exports to manipulate the size of the export table - and the proxy would be completely dynamic. The problem is that the application checks the proxy DLL exports immediately and thus fails (because the expected exports don't exist) before any code can be executed, if there was a way to execute code before failing then this method would be possible. There might be a way that I haven't tested which involves needing 2 DLLs instead of one.

**Comment by techiew** [comment]
After some further thought, attempting proxying of multiple DLLs at once with the macro method can run into conflicts in respect to overlapping ordinals. So that's another difference.

**Comment by NaiJii** [comment]
Glad I could bring extra info to the table!
