### ISSUE TITLE
Usage with Xenos (dll loader)

### ISSUE THREAD

**Issue by SteamKaibz** [techiew/UniversalProxyDLL#6]
I mainly wanted to say thank you for this amazing project. i've been using (and struggling) with proxy dlls for so long and in 5 minutes you just made my life so much easier.

I'm using proxy dlls for my mods but i also sometimes just load the dll with xenos so that i don't have to restart the game all the time, so i just rename the dll and load it it.
But of course because UPD creates proxy based on filename, i can't just name my dll: myGame.dll and expect to load with Xenos as i usually do, any idea how i could make that work somehow?

**Comment by techiew** [comment]
I have never tried it but I guess you could call [FreeLibraryAndExitThread](https://learn.microsoft.com/en-us/windows/win32/api/libloaderapi/nf-libloaderapi-freelibraryandexitthread) from inside your proxy (for example when pressing a key: [GetAsyncKeyState](https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-getasynckeystate)), then when the DLL is unloaded you can load it back in with the same name. Maybe Xenos can unload/uninject DLLs?

**Comment by techiew** [comment]
If that's not an option I guess you could have a DLL somewhat like this: https://github.com/techiew/UniversalProxyDLL/commit/164580d090f7c0625b37fe71d7f52c819df7368a

This would act as kind of your "base" or "master" DLL. The DLL could call LoadLibrary on a specific keypress, or even just repeatedly call LoadLibrary and sleep for a couple seconds in between. Instead of loading DLLs listed in a file as in the example you could load any DLL with a specific postfix or prefix in the working directory (using wildcards). Note that calling LoadLibrary on any DLLs that are already loaded does not do anything, so it should be safe to just spam it willy-nilly.

**Comment by SteamKaibz** [comment]
Thanks techiew,
I think i should have spent a little bit more time thinking before posting.... because the problem i had can be simply fixed by creating a specific build configuration with macros and then use a preprocessor condition to use UPD or not:

```
	#ifndef XENOS_MODE_BUILD
			//UPD::OpenDebugTerminal();
			UPD::CreateProxy(hModule);
	#endif // !XENOS_MODE_BUILD	
```	

Sorry for wasting your time, i'm going to be using UPD in my mod [here](https://www.nexusmods.com/wolfenstein2thenewcolossus/mods/5), i'll make sure to credit you on the description page.

Cheers.

**Comment by techiew** [comment]
Cheers, cool mod.
